---
  - name: install random password gen pack
  apt: name={{item}} state=present
  with_items:
    - apg

  - name: Random gen passwds
  command: apg -n {{ pass_cnt }} -M NCL -q
  register: passwds

  - name: create users
  os_user:
    cloud: "{{ OPS-test1 }}"
    state: present
    name: "{{ item.0 }}"
    password: "{{ item.1 }}"
    domain: default
  with_together:
    - "{{ userid }}"
    - "{{ passwds.stdout_lines }}"

  - name: create users env
  os_project:
    cloud: "{{ OPS-test1 }}"
    state: present
    name: "{{ item }}"
    description: "{{ item }}"
    domain_id: default
    enabled: True
  with_items: "{{ tenantid }}"

  - name: Assign users for spec role env
  os_user_role:
    cloud: "{{ OPS-test1 }}"
    user: "{{ item:0 }}"
    role: "{{ urole }}"
    project: "{{ item.1 }}"
  with_together:
    - "{{ userid }}"
    - "{{ tenantid }}"

  - name: user password assignment
  debug: msg="user {{ item.0 }} added to {{ item.2 }} project, password: {{ item.1 }}"
  with_together:
    - userid
    - passwds.stdout_lines
    - tenantid
   
