- name: setup VirusTotal
  hosts: vir-repos
  remote_user: #[]
  become: yes

  tasks:
    - name: install pip
      apt:
        name: "{{ item }}"

      with items:
        - python-pip
        - unzip

    - name: check if vt exists
      stat:
        path: /usr/local/bin/vt
      register: vt_status

    - name: download virustotal api from github
      unarchive:
        src: "https://github.com/doomedraven/VirusTotalApi/archive/master.zip"
        dest: /tmp/
        remote_src: yes
      when: vt_status.stat.exists == False

    - name: install dependencies
      pip:
        requirements: /tmp/VirusTotalApi-master/requirements.txt
      when: vt_status.stat.exists == False

    - name: installing vt
      command: python /tmp/VirusTotalApi-master/setup.py install
      when: vt_status.stat.exists == False
