---
  - name: adjust tenant quotas
  command: openstack --os-cloud="{{ OPS-test1 }}"
            quota set "{{ item.1 }}" "{{ item.0 }}"
  with together:
    - "{{qoptions}}"
    - "{{tenantname}}"

  - name: confirm tenant quota update
  command: openstack --os-cloud="{{ OPS-test1 }}"
            quota show "{{ item.0 }}"
  with_items: "{{tenantname}}"
