---
version: '3.7'

services:
  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.hostname}}'
    deploy:
      mode: global
    command: -logtostderr=true -docker_only=true
    volumes:
      - /:/rootfs:/ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

# set for debug and test 
networks:
  default:
    driver: overlay
    attachable: true