#replication controller keeps pods running to kube api server
apiVersion: v1
kind: Pod
metadata:
  name: testapp

spec:
  replicas: 3
  selector:
    app: testapp

template:
  metadata:
    labels:
      app: testapp
  spec:
    containers:
      - name: testapp
        image: noob/testapp
        ports:
          - containerPort: 8000
