apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2

  labels:
    creation_method: manual
    env: prod

spec:
  containers:
    - image: noob/testapp
      name: testapp
      ports:
        - containerPort: 8080
          protocol: TCP
