apiVersion: v1
kind: Pod
metadata:
  name: testapp-manual-labels

  labels:
    creation_method: manual
    env: prod

spec:
  containers:
    - image: noob/testapp
      name: testapp
      ports:
        - containerPort: 8000
          protocol: TCP
