---
apiVersion: v1
kind: Pod
metadata:
        name: label-validation
        namespace: infrastructure
        labels:
                controller: label-validator
spec:
        containers:
        - name: label-validator
          image: label-validator:latest
          volumeMounts:
                  - mountPath: /tls
                    name: tls
        volumes:
        - name: tls
          secret:
                  secretName: admission-tls

---
kind: Service
apiVersion: v1
metadata:
        name: label-validation
        namespace: infrastructure
spec:
        selector:
                controller: label-validator
        ports:
                - protocol: TCP
                  port: 443

