apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
        name: label-validation
webhooks:
        - name: admission.example.com
          rules:
                  - apiGroups:
                          - ""
                          apiVersions:
                                  - v1
